### ISSUE TITLE
HTML tags on locked Status

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/PageEditLockFields#1]
Hi Ryan! This is how it looks when you lock the status property:

![image](https://github.com/ryancramerdesign/PageEditLockFields/assets/7663992/d2747f22-15b4-44d1-b17e-19bbc475dbc0)

**Comment by ryancramerdesign** [comment]
The core updates added this week should correct that. But another way is to
enable the "status" field as one that you show the inputs for.

**Comment by matjazpotocnik** [comment]
Yes, the latest updates fix those HTML tags.

I also tried setting the status field to always show inputs, as you suggested, but that has no effect. I tried that with other fields, but no inputs are shown. Maybe I'm doing something wrong?

This is how I set it in the module settings:
![image](https://github.com/ryancramerdesign/PageEditLockFields/assets/7663992/773d9d94-c94f-499c-8920-92f90f6f60b7)

This is what the status field looks like when editing a page:
![image](https://github.com/ryancramerdesign/PageEditLockFields/assets/7663992/3bd0e7ba-342d-4649-b4ae-8812d1585f68)

This is how a field "decimal_in_core" (FieldtypeDecimal) looks like when it's locked but added to the list of fields to show inputs:
![image](https://github.com/ryancramerdesign/PageEditLockFields/assets/7663992/edac99a6-d72b-4d82-a751-87175642f5dd)

**Comment by matjazpotocnik** [comment]
I fixed this by modifying line 748 in lockInputfield() method `$f->collapsed = $this->lockAdjustments[$f->collapsed];` to be `if(!$renderInputs) $f->collapsed = $this->lockAdjustments[$f->collapsed];`

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik I've pushed a fix

**Comment by matjazpotocnik** [comment]
Thanks.
