### ISSUE TITLE
Dragging image thumbnail size slider triggers lock fields dialog

### ISSUE THREAD

**Issue by Toutouwai** [ryancramerdesign/PageEditLockFields#2]
When dragging the thumbnail size slider in an Images field this is detected as a "long click" and the lock fields dialog opens. This probaby isn't what the user is expecting.

![lock](https://github.com/ryancramerdesign/PageEditLockFields/assets/1538852/f79a70d3-f314-44ea-a97f-c447978bd203)

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this

**Comment by Toutouwai** [comment]
Thanks
